name: GoTest

on:
  push:
    branches: [ main,qitmeer ]
  pull_request:
    branches: [ main,qitmeer ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 
        with:
          go-version: 1.16

      - name: Install linter
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

      - name: Test
        run: |
          PATH=$PATH:$(pwd)/build/bin
          export GO111MODULE=on
          go mod tidy
          go test -v ./...
      

